server:
  port: 8080
spring:
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        show_sql : true
        format_sql : true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/ssanolja_2.3?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#    구글
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 441976817988-cvglluv7f5juasiqrqtpuqd41psf8brr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile