server:
  port: 8080
spring:
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/ssanolja_1.3?serverTimezone=Asia/Seoul
    username: root
    password: root