server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: oauth2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        show_sql : false
        format_sql : true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://i6e106.p.ssafy.io:3306/ssanolja_2.7?seUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: root_1234
    driver-class-name: com.mysql.cj.jdbc.Driver


